# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
puts "creating new blog entries"

Blog.create(title: "This is my first blog", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sit amet tempus ex. Nulla sit amet nisi auctor, venenatis purus lobortis, pulvinar nulla. Fusce consectetur velit vitae egestas ultrices. Integer id nisl magna. Cras in urna vestibulum, consectetur leo sit amet, mattis neque. Sed congue dui et ligula suscipit sodales. Maecenas consectetur, felis vehicula tempor accumsan, justo ante dapibus ipsum, sit amet mollis lorem dui sit amet sapien. Nulla non sollicitudin nisi. Nam vitae tempus elit. Aliquam erat volutpat. Etiam efficitur placerat lectus a sodales.")
Blog.create(title: "This is my first blog", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sit amet tempus ex. Nulla sit amet nisi auctor, venenatis purus lobortis, pulvinar nulla. Fusce consectetur velit vitae egestas ultrices. Integer id nisl magna. Cras in urna vestibulum, consectetur leo sit amet, mattis neque. Sed congue dui et ligula suscipit sodales. Maecenas consectetur, felis vehicula tempor accumsan, justo ante dapibus ipsum, sit amet mollis lorem dui sit amet sapien. Nulla non sollicitudin nisi. Nam vitae tempus elit. Aliquam erat volutpat. Etiam efficitur placerat lectus a sodales.")
Blog.create(title: "This is my first blog", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sit amet tempus ex. Nulla sit amet nisi auctor, venenatis purus lobortis, pulvinar nulla. Fusce consectetur velit vitae egestas ultrices. Integer id nisl magna. Cras in urna vestibulum, consectetur leo sit amet, mattis neque. Sed congue dui et ligula suscipit sodales. Maecenas consectetur, felis vehicula tempor accumsan, justo ante dapibus ipsum, sit amet mollis lorem dui sit amet sapien. Nulla non sollicitudin nisi. Nam vitae tempus elit. Aliquam erat volutpat. Etiam efficitur placerat lectus a sodales.")
Blog.create(title: "This is my first blog", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sit amet tempus ex. Nulla sit amet nisi auctor, venenatis purus lobortis, pulvinar nulla. Fusce consectetur velit vitae egestas ultrices. Integer id nisl magna. Cras in urna vestibulum, consectetur leo sit amet, mattis neque. Sed congue dui et ligula suscipit sodales. Maecenas consectetur, felis vehicula tempor accumsan, justo ante dapibus ipsum, sit amet mollis lorem dui sit amet sapien. Nulla non sollicitudin nisi. Nam vitae tempus elit. Aliquam erat volutpat. Etiam efficitur placerat lectus a sodales.")
Blog.create(title: "This is my first blog", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sit amet tempus ex. Nulla sit amet nisi auctor, venenatis purus lobortis, pulvinar nulla. Fusce consectetur velit vitae egestas ultrices. Integer id nisl magna. Cras in urna vestibulum, consectetur leo sit amet, mattis neque. Sed congue dui et ligula suscipit sodales. Maecenas consectetur, felis vehicula tempor accumsan, justo ante dapibus ipsum, sit amet mollis lorem dui sit amet sapien. Nulla non sollicitudin nisi. Nam vitae tempus elit. Aliquam erat volutpat. Etiam efficitur placerat lectus a sodales.")
Blog.create(title: "This is my first blog", content: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc sit amet tempus ex. Nulla sit amet nisi auctor, venenatis purus lobortis, pulvinar nulla. Fusce consectetur velit vitae egestas ultrices. Integer id nisl magna. Cras in urna vestibulum, consectetur leo sit amet, mattis neque. Sed congue dui et ligula suscipit sodales. Maecenas consectetur, felis vehicula tempor accumsan, justo ante dapibus ipsum, sit amet mollis lorem dui sit amet sapien. Nulla non sollicitudin nisi. Nam vitae tempus elit. Aliquam erat volutpat. Etiam efficitur placerat lectus a sodales.")
